/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'date' : string,
  'user' : Principal,
  'timestamp' : bigint,
  'timeSlot' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'booked' : null };
export interface Message {
  'messageType' : MessageType,
  'message' : string,
  'timestamp' : bigint,
  'blobId' : [] | [string],
  'senderRole' : SenderRole,
}
export type MessageType = { 'file' : null } |
  { 'text' : null } |
  { 'image' : null };
export type PointReason = { 'custom' : null } |
  { 'dailyBonus' : null } |
  { 'footsteps' : null } |
  { 'weightImage' : null };
export interface PointRecord {
  'remark' : string,
  'timestamp' : bigint,
  'points' : bigint,
  'reason' : PointReason,
}
export type SenderRole = { 'coach' : null } |
  { 'user' : null };
export interface StreakInfo {
  'daysToNext' : bigint,
  'nextMilestone' : bigint,
  'currentStreak' : bigint,
}
export interface UserProfile {
  'age' : bigint,
  'weight' : string,
  'height' : string,
  'whatsAppNumber' : string,
  'name' : string,
  'email' : string,
  'targetGoal' : string,
  'avatarBlobId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminCancelBooking' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[string, string], bigint>,
  'cancelAllBookingsForUser' : ActorMethod<[Principal], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllBookingsByUser' : ActorMethod<[Principal], Array<Booking>>,
  'getAllBookingsForDate' : ActorMethod<[string], Array<Booking>>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getAvailableTimeSlots' : ActorMethod<[string], Array<[string, boolean]>>,
  'getBookingsByDate' : ActorMethod<[string], Array<Booking>>,
  'getCallerPointHistory' : ActorMethod<[], Array<PointRecord>>,
  'getCallerPoints' : ActorMethod<[], bigint>,
  'getCallerStreak' : ActorMethod<[], StreakInfo>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLastReadTimestamp' : ActorMethod<[Principal], [] | [bigint]>,
  'getMessageHistory' : ActorMethod<[], Array<Message>>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'getUserMessageHistory' : ActorMethod<[Principal], Array<Message>>,
  'getUserPointHistory' : ActorMethod<[Principal], Array<PointRecord>>,
  'getUserPoints' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'givePoints' : ActorMethod<[Principal, bigint, PointReason, string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessagesAsRead' : ActorMethod<[], undefined>,
  'recordActivity' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessageToCoach' : ActorMethod<
    [string, MessageType, [] | [string]],
    undefined
  >,
  'sendMessageToUser' : ActorMethod<
    [Principal, string, MessageType, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];