/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'booked' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'date' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'timeSlot' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Text,
  'height' : IDL.Text,
  'whatsAppNumber' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'targetGoal' : IDL.Text,
  'avatarBlobId' : IDL.Opt(IDL.Text),
});
export const PointReason = IDL.Variant({
  'custom' : IDL.Null,
  'dailyBonus' : IDL.Null,
  'footsteps' : IDL.Null,
  'weightImage' : IDL.Null,
});
export const PointRecord = IDL.Record({
  'remark' : IDL.Text,
  'timestamp' : IDL.Int,
  'points' : IDL.Nat,
  'reason' : PointReason,
});
export const StreakInfo = IDL.Record({
  'daysToNext' : IDL.Nat,
  'nextMilestone' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const MessageType = IDL.Variant({
  'file' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const SenderRole = IDL.Variant({
  'coach' : IDL.Null,
  'user' : IDL.Null,
});
export const Message = IDL.Record({
  'messageType' : MessageType,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'blobId' : IDL.Opt(IDL.Text),
  'senderRole' : SenderRole,
});

export const idlService = IDL.Service({
  'adminCancelBooking' : IDL.Func([IDL.Nat], [], []),
  'bookAppointment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'cancelAllBookingsForUser' : IDL.Func([IDL.Principal], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllBookingsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getAllBookingsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAvailableTimeSlots' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerPointHistory' : IDL.Func([], [IDL.Vec(PointRecord)], ['query']),
  'getCallerPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerStreak' : IDL.Func([], [StreakInfo], ['query']),
  'getCallerUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCoachUnreadCountForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat],
      ['query'],
    ),
  'getLastReadTimestamp' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Int)],
      ['query'],
    ),
  'getMessageHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserMessageHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserPointHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PointRecord)],
      ['query'],
    ),
  'getUserPoints' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'givePoints' : IDL.Func(
      [IDL.Principal, IDL.Nat, PointReason, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'markCoachReadForUser' : IDL.Func([IDL.Principal], [], []),
  'markMessagesAsRead' : IDL.Func([], [], []),
  'recordActivity' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessageToCoach' : IDL.Func(
      [IDL.Text, MessageType, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'sendMessageToUser' : IDL.Func(
      [IDL.Principal, IDL.Text, MessageType, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'booked' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'date' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'timeSlot' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Text,
    'height' : IDL.Text,
    'whatsAppNumber' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'targetGoal' : IDL.Text,
    'avatarBlobId' : IDL.Opt(IDL.Text),
  });
  const PointReason = IDL.Variant({
    'custom' : IDL.Null,
    'dailyBonus' : IDL.Null,
    'footsteps' : IDL.Null,
    'weightImage' : IDL.Null,
  });
  const PointRecord = IDL.Record({
    'remark' : IDL.Text,
    'timestamp' : IDL.Int,
    'points' : IDL.Nat,
    'reason' : PointReason,
  });
  const StreakInfo = IDL.Record({
    'daysToNext' : IDL.Nat,
    'nextMilestone' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const MessageType = IDL.Variant({
    'file' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const SenderRole = IDL.Variant({ 'coach' : IDL.Null, 'user' : IDL.Null });
  const Message = IDL.Record({
    'messageType' : MessageType,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'blobId' : IDL.Opt(IDL.Text),
    'senderRole' : SenderRole,
  });
  
  return IDL.Service({
    'adminCancelBooking' : IDL.Func([IDL.Nat], [], []),
    'bookAppointment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'cancelAllBookingsForUser' : IDL.Func([IDL.Principal], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllBookingsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getAllBookingsForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAvailableTimeSlots' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerPointHistory' : IDL.Func([], [IDL.Vec(PointRecord)], ['query']),
    'getCallerPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerStreak' : IDL.Func([], [StreakInfo], ['query']),
    'getCallerUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCoachUnreadCountForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getLastReadTimestamp' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Int)],
        ['query'],
      ),
    'getMessageHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserMessageHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserPointHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PointRecord)],
        ['query'],
      ),
    'getUserPoints' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'givePoints' : IDL.Func(
        [IDL.Principal, IDL.Nat, PointReason, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'markCoachReadForUser' : IDL.Func([IDL.Principal], [], []),
    'markMessagesAsRead' : IDL.Func([], [], []),
    'recordActivity' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessageToCoach' : IDL.Func(
        [IDL.Text, MessageType, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'sendMessageToUser' : IDL.Func(
        [IDL.Principal, IDL.Text, MessageType, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };