/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StreakInfo {
    daysToNext: bigint;
    nextMilestone: bigint;
    currentStreak: bigint;
}
export interface Message {
    messageType: MessageType;
    message: string;
    timestamp: bigint;
    blobId?: string;
    senderRole: SenderRole;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    date: string;
    user: Principal;
    timestamp: bigint;
    timeSlot: string;
}
export interface PointRecord {
    remark: string;
    timestamp: bigint;
    points: bigint;
    reason: PointReason;
}
export interface UserProfile {
    age: bigint;
    weight: string;
    height: string;
    whatsAppNumber: string;
    name: string;
    email: string;
    targetGoal: string;
    avatarBlobId?: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    booked = "booked"
}
export enum MessageType {
    file = "file",
    text = "text",
    image = "image"
}
export enum PointReason {
    custom = "custom",
    dailyBonus = "dailyBonus",
    footsteps = "footsteps",
    weightImage = "weightImage"
}
export enum SenderRole {
    coach = "coach",
    user = "user"
}
export interface backendInterface {
    adminCancelBooking(bookingId: bigint): Promise<void>;
    bookAppointment(date: string, timeSlot: string): Promise<bigint>;
    cancelAllBookingsForUser(user: Principal): Promise<void>;
    cancelBooking(bookingId: bigint): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllBookingsByUser(user: Principal): Promise<Array<Booking>>;
    getAllBookingsForDate(date: string): Promise<Array<Booking>>;
    getAllProfiles(): Promise<Array<UserProfile>>;
    getAllUsers(): Promise<Array<Principal>>;
    getAvailableTimeSlots(date: string): Promise<Array<[string, boolean]>>;
    getBookingsByDate(date: string): Promise<Array<Booking>>;
    getCallerPointHistory(): Promise<Array<PointRecord>>;
    getCallerPoints(): Promise<bigint>;
    getCallerStreak(): Promise<StreakInfo>;
    getCallerUnreadCount(): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCoachUnreadCountForUser(user: Principal): Promise<bigint>;
    getLastReadTimestamp(user: Principal): Promise<bigint | null>;
    getMessageHistory(): Promise<Array<Message>>;
    getUserBookings(): Promise<Array<Booking>>;
    getUserMessageHistory(user: Principal): Promise<Array<Message>>;
    getUserPointHistory(user: Principal): Promise<Array<PointRecord>>;
    getUserPoints(user: Principal): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    givePoints(user: Principal, points: bigint, reason: PointReason, remark: string): Promise<bigint>;
    markCoachReadForUser(user: Principal): Promise<void>;
    markMessagesAsRead(): Promise<void>;
    recordActivity(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessageToCoach(message: string, messageType: MessageType, blobId: string | null): Promise<void>;
    sendMessageToUser(user: Principal, message: string, messageType: MessageType, blobId: string | null): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Message as _Message, MessageType as _MessageType, PointReason as _PointReason, PointRecord as _PointRecord, SenderRole as _SenderRole, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminCancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCancelBooking(arg0);
            return result;
        }
    }
    async bookAppointment(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1);
            return result;
        }
    }
    async cancelAllBookingsForUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAllBookingsForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAllBookingsForUser(arg0);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookingsByUser(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingsByUser(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingsByUser(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookingsForDate(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingsForDate(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingsForDate(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAvailableTimeSlots(arg0: string): Promise<Array<[string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots(arg0);
            return result;
        }
    }
    async getBookingsByDate(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDate(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDate(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPointHistory(): Promise<Array<PointRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPointHistory();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPointHistory();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPoints(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPoints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPoints();
            return result;
        }
    }
    async getCallerStreak(): Promise<StreakInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStreak();
            return result;
        }
    }
    async getCallerUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUnreadCount();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachUnreadCountForUser(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachUnreadCountForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachUnreadCountForUser(arg0);
            return result;
        }
    }
    async getLastReadTimestamp(arg0: Principal): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastReadTimestamp(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastReadTimestamp(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageHistory(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageHistory();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageHistory();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMessageHistory(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMessageHistory(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMessageHistory(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPointHistory(arg0: Principal): Promise<Array<PointRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPointHistory(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPointHistory(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPoints(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPoints(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async givePoints(arg0: Principal, arg1: bigint, arg2: PointReason, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.givePoints(arg0, arg1, to_candid_PointReason_n24(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.givePoints(arg0, arg1, to_candid_PointReason_n24(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async markCoachReadForUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markCoachReadForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCoachReadForUser(arg0);
            return result;
        }
    }
    async markMessagesAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesAsRead();
            return result;
        }
    }
    async recordActivity(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordActivity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordActivity();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessageToCoach(arg0: string, arg1: MessageType, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageToCoach(arg0, to_candid_MessageType_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageToCoach(arg0, to_candid_MessageType_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async sendMessageToUser(arg0: Principal, arg1: string, arg2: MessageType, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageToUser(arg0, arg1, to_candid_MessageType_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageToUser(arg0, arg1, to_candid_MessageType_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_BookingStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MessageType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PointReason_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointReason): PointReason {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PointRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointRecord): PointRecord {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SenderRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SenderRole): SenderRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    remark: string;
    timestamp: bigint;
    points: bigint;
    reason: _PointReason;
}): {
    remark: string;
    timestamp: bigint;
    points: bigint;
    reason: PointReason;
} {
    return {
        remark: value.remark,
        timestamp: value.timestamp,
        points: value.points,
        reason: from_candid_PointReason_n13(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messageType: _MessageType;
    message: string;
    timestamp: bigint;
    blobId: [] | [string];
    senderRole: _SenderRole;
}): {
    messageType: MessageType;
    message: string;
    timestamp: bigint;
    blobId?: string;
    senderRole: SenderRole;
} {
    return {
        messageType: from_candid_MessageType_n20(_uploadFile, _downloadFile, value.messageType),
        message: value.message,
        timestamp: value.timestamp,
        blobId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.blobId)),
        senderRole: from_candid_SenderRole_n22(_uploadFile, _downloadFile, value.senderRole)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    date: string;
    user: Principal;
    timestamp: bigint;
    timeSlot: string;
}): {
    id: bigint;
    status: BookingStatus;
    date: string;
    user: Principal;
    timestamp: bigint;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n4(_uploadFile, _downloadFile, value.status),
        date: value.date,
        user: value.user,
        timestamp: value.timestamp,
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: string;
    height: string;
    whatsAppNumber: string;
    name: string;
    email: string;
    targetGoal: string;
    avatarBlobId: [] | [string];
}): {
    age: bigint;
    weight: string;
    height: string;
    whatsAppNumber: string;
    name: string;
    email: string;
    targetGoal: string;
    avatarBlobId?: string;
} {
    return {
        age: value.age,
        weight: value.weight,
        height: value.height,
        whatsAppNumber: value.whatsAppNumber,
        name: value.name,
        email: value.email,
        targetGoal: value.targetGoal,
        avatarBlobId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.avatarBlobId))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    dailyBonus: null;
} | {
    footsteps: null;
} | {
    weightImage: null;
}): PointReason {
    return "custom" in value ? PointReason.custom : "dailyBonus" in value ? PointReason.dailyBonus : "footsteps" in value ? PointReason.footsteps : "weightImage" in value ? PointReason.weightImage : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: null;
} | {
    text: null;
} | {
    image: null;
}): MessageType {
    return "file" in value ? MessageType.file : "text" in value ? MessageType.text : "image" in value ? MessageType.image : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coach: null;
} | {
    user: null;
}): SenderRole {
    return "coach" in value ? SenderRole.coach : "user" in value ? SenderRole.user : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    booked: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "booked" in value ? BookingStatus.booked : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PointRecord>): Array<PointRecord> {
    return value.map((x)=>from_candid_PointRecord_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n7(_uploadFile, _downloadFile, x));
}
function to_candid_MessageType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_PointReason_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PointReason): _PointReason {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: string;
    height: string;
    whatsAppNumber: string;
    name: string;
    email: string;
    targetGoal: string;
    avatarBlobId?: string;
}): {
    age: bigint;
    weight: string;
    height: string;
    whatsAppNumber: string;
    name: string;
    email: string;
    targetGoal: string;
    avatarBlobId: [] | [string];
} {
    return {
        age: value.age,
        weight: value.weight,
        height: value.height,
        whatsAppNumber: value.whatsAppNumber,
        name: value.name,
        email: value.email,
        targetGoal: value.targetGoal,
        avatarBlobId: value.avatarBlobId ? candid_some(value.avatarBlobId) : candid_none()
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PointReason): {
    custom: null;
} | {
    dailyBonus: null;
} | {
    footsteps: null;
} | {
    weightImage: null;
} {
    return value == PointReason.custom ? {
        custom: null
    } : value == PointReason.dailyBonus ? {
        dailyBonus: null
    } : value == PointReason.footsteps ? {
        footsteps: null
    } : value == PointReason.weightImage ? {
        weightImage: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    file: null;
} | {
    text: null;
} | {
    image: null;
} {
    return value == MessageType.file ? {
        file: null
    } : value == MessageType.text ? {
        text: null
    } : value == MessageType.image ? {
        image: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
